### PR TITLE
Call "initialize" after setInput

### PR DESCRIPTION
**Pull request by alidd**

### CODE REVIEW

**Comment by Page-** [comment]
I'd rather call initialise just once upon creating the instance so that it's possible/easy to keep the one-off initialisation behaviour. However I'd be all for adding a `reset` (or some other name?) method which is called before each setInput, and is used to reset to any defaults that are necessary.  Would this work for you?

**Comment by alidd** [comment]
I would't like to introduce a new method here, because I'm interested in better compatibility between different ometa-js forks: "multiple implementations are good, but not multiple dialects".

With the original ometa-js one can use a grammar
- either by calling `match` or `matchAll` on grammar itself, having both methods delegating to `_genericMatch`, which by each call creates a new instance with preset input and then calls `initialize`:

```
 var m = objectThatDelegatesTo(this, {input: input})
 m.initialize()
```
- or by calling `createInstance` which returns a single already initialized instance with overwritten `matchAll` and then repeatedly calling `matchAll` on it. The `createInstance` method, was introduced as answer to [Stateful Parsers?](http://vpri.org/pipermail/ometa/2010-November/000342.html) thread at OMeta mailing list.

I have just created a new PR to reflect this behavior.
What do you think?

**Comment by Page-** [comment]
Ok, so if I'm understanding this right the issue is that the `initialize` function no longer has the input available? Am I right in this understanding? And if so do you have a use case for this?

**Comment by alidd** [comment]
Yes. Yes. No more (have rewritten my parsers to not use initialize at all).
Should I close both PRs?

**Comment by Page-** [comment]
Yeah, I really don't think the `initialize` function should be making use of the input - that's the job of the grammar, not the initialize function. So whilst I acknowledge that Alex's original implementation does it differently (and I'd rather avoid incompatibilities if I can), I think the current behaviour makes more sense in the balance of things.

**Pull request closed without merging**
